#!/usr/bin/env ruby
# -*- ruby -*-
puts "Building configuration..."
begin
  require 'rubygems'
rescue LoadError
end
require 'yaml'

CONFIG_PATH = File.dirname(__FILE__)
NGINX_PORT = 80
APACHE_PORT = 8080

# No syntax checking whatsoever on the yaml files. You're on your own.

class Vhost

  def initialize(args)
    # This might be dangerous? I'm pretty sure we can trust whoever's
    # writing our vhost definitions :)
    instance_variable_set "@nginx_port", NGINX_PORT
    instance_variable_set "@apache_port", APACHE_PORT
    args.each do |k,v|
      instance_variable_set "@#{k}", v
    end
    @template ||= 'static'
    # We need to wrap @location in slashes, but if it's root, that gives us
    #   // or ///, so we collapse multiple sequential slashes to a single /.
    @location = "/#{@location}/"
    @location.gsub!(/\/+/,'/')
    
    @templates = YAML.load(open("#{CONFIG_PATH}/templates.yml"))
  end

  # Again, this is stupid. However, if we can't trust the people writing our
  #  config.yml, we have bigger problems.
  def apache_config
    if @templates.has_key? @template
      eval("return \"#{@templates[@template]['content_for_apache']}\"")
    end
  end

  def nginx_config
    if @templates.has_key? @template
      eval("return \"#{@templates[@template]['content_for_nginx']}\"")
    end
  end

end

nginx_config  = ""
apache_config = ""

hosts = YAML.load(open("#{CONFIG_PATH}/config.yml"))

begin
  hosts.each do |k,v|
    vhost = Vhost.new(v.merge({'domain' => k}))
    nginx_config  << vhost.nginx_config
    apache_config << vhost.apache_config
  end
rescue
	puts "[Failure: Syntax error in config.yml]"
  exit 1
end
# Write the output file and commit it to git.
File.open("#{CONFIG_PATH}/gen/nginx.gen.conf",'w') do |f|
  f.puts nginx_config
end
File.open("#{CONFIG_PATH}/gen/apache.gen.conf",'w') do |f|
  f.puts apache_config
end

unless system("sudo nginx -t > /dev/null 2>/dev/null")
  puts "[Failure: Nginx Config Invalid]"
  exit 1
end

unless system("apachectl -t > /dev/null 2>/dev/null")
  puts "[Failure: Apache Config Invalid]"
  exit 1
end

puts "[success]"
